package nic.transport.homologation.web.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2019-12-17T18:42:47.796+05:30
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://service.web.homologation.transport.nic/", name = "dataportws")
@XmlSeeAlso({ObjectFactory.class})
public interface Dataportws {

    @WebMethod
    @RequestWrapper(localName = "upload", targetNamespace = "http://service.web.homologation.transport.nic/", className = "nic.transport.homologation.web.service.Upload")
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://service.web.homologation.transport.nic/", className = "nic.transport.homologation.web.service.UploadResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String upload(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId,
        @WebParam(name = "transactionId", targetNamespace = "")
        java.lang.String transactionId,
        @WebParam(name = "inventoryDetails", targetNamespace = "")
        java.util.List<nic.transport.homologation.web.service.InventoryDetailsDobj> inventoryDetails
    );
}
