package com.sap.document.sap.soap.functions.mc_style;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2019-12-12T23:36:02.361+05:30
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", name = "ZSDRFC_AMC_CLAIM_GENERATION")
@XmlSeeAlso({ObjectFactory.class})
public interface ZSDRFCAMCCLAIMGENERATION {

    @WebMethod(operationName = "ZsdrfcAmcClaimGeneration", action = "urn:sap-com:document:sap:soap:functions:mc-style:ZSDRFC_AMC_CLAIM_GENERATION:ZsdrfcAmcClaimGenerationRequest")
    @RequestWrapper(localName = "ZsdrfcAmcClaimGeneration", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZsdrfcAmcClaimGeneration_Type")
    @ResponseWrapper(localName = "ZsdrfcAmcClaimGenerationResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZsdrfcAmcClaimGenerationResponse")
    public void zsdrfcAmcClaimGeneration(
        @WebParam(name = "ChassiNo", targetNamespace = "")
        java.lang.String chassiNo,
        @WebParam(name = "ChassisPl", targetNamespace = "")
        java.lang.String chassisPl,
        @WebParam(mode = WebParam.Mode.INOUT, name = "ClaimItem", targetNamespace = "")
        javax.xml.ws.Holder<TableOfZstAmcClmDtl> claimItem,
        @WebParam(name = "ClaimType", targetNamespace = "")
        java.lang.String claimType,
        @WebParam(name = "ContractAndItem", targetNamespace = "")
        java.lang.String contractAndItem,
        @WebParam(name = "ContractNo", targetNamespace = "")
        java.lang.String contractNo,
        @WebParam(name = "CrmClaimNo", targetNamespace = "")
        java.lang.String crmClaimNo,
        @WebParam(name = "CrmSaleDate", targetNamespace = "")
        java.lang.String crmSaleDate,
        @WebParam(name = "DealerCode", targetNamespace = "")
        java.lang.String dealerCode,
        @WebParam(name = "JobCardDate", targetNamespace = "")
        java.lang.String jobCardDate,
        @WebParam(name = "JobCardNo", targetNamespace = "")
        java.lang.String jobCardNo,
        @WebParam(name = "JobClosDate", targetNamespace = "")
        java.lang.String jobClosDate,
        @WebParam(name = "JobClosDateI", targetNamespace = "")
        java.lang.String jobClosDateI,
        @WebParam(name = "KmRead", targetNamespace = "")
        int kmRead,
        @WebParam(name = "LabourAmtCrm", targetNamespace = "")
        java.math.BigDecimal labourAmtCrm,
        @WebParam(name = "LubChargeCrm", targetNamespace = "")
        java.math.BigDecimal lubChargeCrm,
        @WebParam(name = "MaterialAmtCrm", targetNamespace = "")
        java.math.BigDecimal materialAmtCrm,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Return", targetNamespace = "")
        javax.xml.ws.Holder<TableOfBapiret2> _return,
        @WebParam(name = "SaveData", targetNamespace = "")
        java.lang.String saveData,
        @WebParam(name = "SplChargeCrm", targetNamespace = "")
        java.math.BigDecimal splChargeCrm,
        @WebParam(name = "TotalChargeCrm", targetNamespace = "")
        java.math.BigDecimal totalChargeCrm,
        @WebParam(name = "ZauthNo", targetNamespace = "")
        java.lang.String zauthNo,
        @WebParam(mode = WebParam.Mode.OUT, name = "ClaimNo", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> claimNo
    );
}
