package com.sap.document.sap.soap.functions.mc_style;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2019-12-12T23:36:02.391+05:30
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "ZSDRFC_AMC_CLAIM_GENERATION",
                  wsdlLocation = "file:/home/redhat/TML-Proejcts/AMC_Latest_12Dec/amc-claim-master/src/main/resources/esb/ESB_amc_claim_generation_dev.wsdl",
                  targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
public class ZSDRFCAMCCLAIMGENERATION_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZSDRFC_AMC_CLAIM_GENERATION");
    public final static QName ZSDRFCAMCCLAIMGENERATION = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZSDRFC_AMC_CLAIM_GENERATION");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/redhat/TML-Proejcts/AMC_Latest_12Dec/amc-claim-master/src/main/resources/esb/ESB_amc_claim_generation_dev.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZSDRFCAMCCLAIMGENERATION_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/home/redhat/TML-Proejcts/AMC_Latest_12Dec/amc-claim-master/src/main/resources/esb/ESB_amc_claim_generation_dev.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZSDRFCAMCCLAIMGENERATION_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZSDRFCAMCCLAIMGENERATION_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZSDRFCAMCCLAIMGENERATION_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ZSDRFCAMCCLAIMGENERATION_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ZSDRFCAMCCLAIMGENERATION_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ZSDRFCAMCCLAIMGENERATION_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ZSDRFCAMCCLAIMGENERATION
     */
    @WebEndpoint(name = "ZSDRFC_AMC_CLAIM_GENERATION")
    public ZSDRFCAMCCLAIMGENERATION getZSDRFCAMCCLAIMGENERATION() {
        return super.getPort(ZSDRFCAMCCLAIMGENERATION, ZSDRFCAMCCLAIMGENERATION.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZSDRFCAMCCLAIMGENERATION
     */
    @WebEndpoint(name = "ZSDRFC_AMC_CLAIM_GENERATION")
    public ZSDRFCAMCCLAIMGENERATION getZSDRFCAMCCLAIMGENERATION(WebServiceFeature... features) {
        return super.getPort(ZSDRFCAMCCLAIMGENERATION, ZSDRFCAMCCLAIMGENERATION.class, features);
    }

}
