kind: 'BuildConfig'
apiVersion: 'v1'
metadata:
  name: 'bulk-insert-jdg'
  namespace: cicd
spec:
  source:
    git:
      ref: master
      uri: 'https://github.com/omkarttl/JDG_Bulk_Insert.git'
    sourceSecret:
      name: github-op
  strategy:
    jenkinsPipelineStrategy:
      env:
      - name: PROJECT
        value: dev-esb
      jenkinsfilePath: 'Jenkinsfile'
