package com.sap.document.sap.rfc.functions;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2019-12-12T22:20:50.847+05:30
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "ZSDRFC_AMC_CONTRACT_VALIDATION",
                  wsdlLocation = "file:/C:/Users/omkarp.ttl/Desktop/combiningWsdl-master/amc-claim-master/src/main/resources/esb/ESB_amc_contract_validation_dev.wsdl",
                  targetNamespace = "urn:sap-com:document:sap:rfc:functions")
public class ZSDRFCAMCCONTRACTVALIDATION_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:rfc:functions", "ZSDRFC_AMC_CONTRACT_VALIDATION");
    public final static QName ZSDRFCAMCCONTRACTVALIDATION = new QName("urn:sap-com:document:sap:rfc:functions", "ZSDRFC_AMC_CONTRACT_VALIDATION");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/omkarp.ttl/Desktop/combiningWsdl-master/amc-claim-master/src/main/resources/esb/ESB_amc_contract_validation_dev.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZSDRFCAMCCONTRACTVALIDATION_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/omkarp.ttl/Desktop/combiningWsdl-master/amc-claim-master/src/main/resources/esb/ESB_amc_contract_validation_dev.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZSDRFCAMCCONTRACTVALIDATION_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZSDRFCAMCCONTRACTVALIDATION_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZSDRFCAMCCONTRACTVALIDATION_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ZSDRFCAMCCONTRACTVALIDATION_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ZSDRFCAMCCONTRACTVALIDATION_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ZSDRFCAMCCONTRACTVALIDATION_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ZSDRFCAMCCONTRACTVALIDATION
     */
    @WebEndpoint(name = "ZSDRFC_AMC_CONTRACT_VALIDATION")
    public ZSDRFCAMCCONTRACTVALIDATION getZSDRFCAMCCONTRACTVALIDATION() {
        return super.getPort(ZSDRFCAMCCONTRACTVALIDATION, ZSDRFCAMCCONTRACTVALIDATION.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZSDRFCAMCCONTRACTVALIDATION
     */
    @WebEndpoint(name = "ZSDRFC_AMC_CONTRACT_VALIDATION")
    public ZSDRFCAMCCONTRACTVALIDATION getZSDRFCAMCCONTRACTVALIDATION(WebServiceFeature... features) {
        return super.getPort(ZSDRFCAMCCONTRACTVALIDATION, ZSDRFCAMCCONTRACTVALIDATION.class, features);
    }

}
