package com.sap.document.sap.rfc.functions;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2019-12-12T22:20:50.818+05:30
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:rfc:functions", name = "ZSDRFC_AMC_CONTRACT_VALIDATION")
@XmlSeeAlso({ObjectFactory.class})
public interface ZSDRFCAMCCONTRACTVALIDATION {

    @WebMethod(operationName = "ZSDRFC_AMC_CONTRACT_VALIDATION", action = "urn:sap-com:document:sap:rfc:functions:ZSDRFC_AMC_CONTRACT_VALIDATION:ZSDRFC_AMC_CONTRACT_VALIDATIONRequest")
    @RequestWrapper(localName = "ZSDRFC_AMC_CONTRACT_VALIDATION", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.sap.document.sap.rfc.functions.ZSDRFCAMCCONTRACTVALIDATION_Type")
    @ResponseWrapper(localName = "ZSDRFC_AMC_CONTRACT_VALIDATIONResponse", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.sap.document.sap.rfc.functions.ZSDRFCAMCCONTRACTVALIDATIONResponse")
    public void zsdrfcAMCCONTRACTVALIDATION(
        @WebParam(name = "CHASSIS_NO", targetNamespace = "")
        java.lang.String chassisNO,
        @WebParam(name = "CHASSIS_PL", targetNamespace = "")
        java.lang.String chassisPL,
        @WebParam(name = "CONTRACT_NO", targetNamespace = "")
        java.lang.String contractNO,
        @WebParam(name = "CRM_SALE_DATE", targetNamespace = "")
        java.lang.String crmSALEDATE,
        @WebParam(mode = WebParam.Mode.INOUT, name = "IT_AMC", targetNamespace = "")
        javax.xml.ws.Holder<TABLEOFZSDAMCLINEITEM> itAMC,
        @WebParam(name = "KMS", targetNamespace = "")
        int kms,
        @WebParam(mode = WebParam.Mode.OUT, name = "REMARKS", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> remarks
    );
}
