kind: 'BuildConfig'
apiVersion: 'v1'
metadata:
  name: 'account-extract-api'
  namespace: cicd
spec:
  source:
    git:
      ref: master
      uri: 'https://github.com/tmlconnected/AIP_ACCOUNT_EXTRACT.git'
    sourceSecret:
      name: github-op  
  strategy:
    jenkinsPipelineStrategy:
      env:
      - name: PROJECT
        value: dev-esb
      jenkinsfilePath: 'Jenkinsfile'
