kind: 'BuildConfig'
apiVersion: 'v1'
metadata:
  name: 'production-booking-pipeline'
  namespace: cicd
spec:
  source:
    git:
      ref: master
      uri: 'https://github.com/tmlconnected/AIP_MES.git'
    sourceSecret:
      name: github-op 
  strategy:
    jenkinsPipelineStrategy:
      env:
      - name: PROJECT
        value: dev-esb
      jenkinsfilePath: 'Jenkinsfile'
